### ISSUE TITLE
Consultor de Bíblia

### ISSUE THREAD

**Issue by fnandoleal** [bsjaramillo/scriptscommunity#1]
[Bíblia.js.zip](https://github.com/bsjaramillo/scriptscommunity/files/11860289/Biblia.js.zip) Esse roteiro pode consultar trechos da Bíblia. Por enquanto a pesquisa é feita pelo livro em inglês. Pode ser editado o arquivo pra outros idiomas. Exemplo de comando: /Bíblia James2:1-6

**Comment by bsjaramillo** [comment]
Please, dont use special chars (accents) for file names and commands, It could to get error and the script could not works right.

**Comment by fnandoleal** [comment]
> Please, dont use special chars (accents) for file names and commands, It could to get error and the script could not works right.
Livre pra edição caso desejar.

**Comment by bsjaramillo** [comment]
I'm not going to fix or improve any script, I'm just going to post it.
